# Site settings
title: Lizhao Blog
name: Lizhao # your name
email: l_zemail@163.com # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
# twitter_username: # your Twitter username
github_username: thelizhao # your Github username
# disqus_username: # your disqus username

# google-analytics: # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
